# Page settings
baseurl = "http://busi-scraping.tk/"
title = "Business base scraping"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = "特定サイトからの情報収集・リスト作成サービスを提供しています。企業情報・物件情報などあらゆるサイトから顧客の欲しい情報をピックアップし、あなたの業務を手助けします。"
  email = ""
  # Navigation
  [params.navigation]
    brand = "Business base scraping"
    home = "Home"
    work = "Work"
    testimonials = "Price"
    services = "Services"
    about = "Price"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Turn web content into useful data for your next great move"
    subtitle = 'スクレイピングによる情報収集・データベース作成サービス'
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Valuable Data"
    description = "プログラムを作成し、瞬時にデータを取ることでリアルタイムなデータを抽出。"
    url = "work"
    button = "Get In Touch"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Custom Solution"
    description = "スクレイピング技術を利用し、お客様のニーズに沿ったデータを作成します。"
    url = "services"
    button = "Click Me"
    icon = "icon-wrench"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "Best Price"
    description = "何万件ものデータを瞬時にかつリーズナブルな価格でご提供します。"
    url = "about"
    button = "Price"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [params.intro.video]
    enable = true
    title = "Watch the video"
    icon = "icon-play2"
    url = "https://www.youtube.com/embed/2yatQH-zcTw"


  # Work section
  [params.work]
    enable = true
    title = "Work"
    description = "リスト作成には数多くの工数がかかります。Business Base Scrapingは、営業経験者だからこそ理解できる営業マン向けのリスト作成を瞬時に行います。"
    footertext = '<a href="http://busi-base.tk/database" class="btn btn-primary">Visit our website</a>'

    [[params.work.row]]
      img = "work_1.png"
      alt = "Image2"
      title = "Project 1"
      subtitle = "VCリスト"
      

    [[params.work.row]]
      img = "work_2.png"
      alt = "Image2"
      title = "Project 2"
      subtitle = "ブロックチェーンリスト"

    [[params.work.row]]
      img = "work_3.png"
      alt = "Image3"
      title = "Project 3"
      subtitle = "映画リスト"

    

  # Testimonials section
  [params.testimonials]
    enable = false
    title = "price"
    description = "Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts."

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in Bookmarksgrove right at the coast of the Semantics, a large language ocean.&rdquo;"
      person = 'Jean Doe, CEO <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = ""
      person = 'John Doe, Senior UI <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = "&ldquo;Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. &rdquo;"
      person = 'Chris Nash, Director <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> <span class="subtext">Creative Director</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "Services"
    description = "特定サイトから選択された情報・項目などに従ってカスタマイズされたデータベースの作成を行います。"

    [[params.services.item]]
      title = "セールスリスト作成"
      description = "特定のサイトからセールスリストを作成します。"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "リクルートメント"
      description = "求人サイトなどから情報を抽出し、競合の分析・リクルートなどに役立たせます。"
      icon = "icon-layers2"

    [[params.services.item]]
      title = "マーケティング"
      description = "SNSは現在マーケティングにおいて最も貴重な情報源です。キーワードでトラッキングし、それをデータ化します。"
      icon = "icon-video2"

      [[params.services.item]]
      title = "不動産データ"
      description = "物件情報の取得から比較までを行い、意思決定に貢献します。"      
      icon = "icon-monitor"


  # About section
  [params.about]
    enable = true
    title = "Price"
    description = "取得件数によるお客様のニーズにあった3タイプをご用意"


[[params.about.item]]
    title = "プランA"
    description = "営業リストなど、短時間で最低限の情報リストが欲しい"
    date = "100~1000件(1~3日)"
    price = "¥15/件"
    url = "contact"
    button = "Plan A"
    icon = "icon-rocket"
    img = "img_10.jpg"

[[params.about.item]]
    title = "プランB"
    description = "マーケティングのために短時間かつ情報量の多いリストが欲しい"
    date = "5001~10000件(3~5日)"
    price = "¥8円/件"
    url = "contact"
    button = "Plan B"
    icon = "icon-bulb"
    img = "img_7.jpg"

  [[params.about.item]]
    title = "プランC"
    description = "サイトの更新などのための莫大な情報量・項目が欲しい"
    date = "10001件〜(3~10日)"
    price = "¥5/件"
    url = "contact"
    button = "Plan C"
    icon = "icon-wrench"
    img = "img_8.jpg"



  # Counters section
  [params.counters]
    enable = true
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = ""
    
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-envelope", "busi.base.tk@gmail.com"],
        ["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Business base scraping All Rights Reserved.'     
    links = [
        ["icon-twitter", "https://www.twitter.com/innovative_usjp"],
        ["icon-facebook", "https://www.facebook.com/busibase"],
        ["icon-youtube", "https://www.youtube.com/watch?v=ggieY5leUm0"]
      ]
